### ISSUE TITLE
Can we have the SIGNUP link now?

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscafrica/oscafrica.org-v1#15]
Can we have the link to the google form now or are we not ready to begin registration?

**Comment by samswag** [comment]
Yes, we can. I will email @Yomdroid to open it

**Comment by yomaokobiah** [comment]
I embedded the link on the website already, It's just not open yet. @samswag should the link be open for registrations now?

**Comment by samswag** [comment]
Yes, you can open the links.

**Comment by BolajiAyodeji** [comment]
@Yomdroid shorten the url before embedding

**Comment by yomaokobiah** [comment]
its already embedded, later I can shorten it and replace @BolajiAyodeji 
@samswag its open now

**Comment by BolajiAyodeji** [comment]
@Yomdroid add to navbar and other sections where needed

**Comment by BolajiAyodeji** [comment]
@Yomdroid the form contents are not arranged properly.
email appears twice, email in between first and last name.
Please fix
