### ISSUE TITLE
Refactor the CSS styles using SASS

### ISSUE THREAD

**Issue by kodekage** [oscafrica/oscafrica.org-v1#18]
**Is your feature request related to a problem? Please describe.**
The current CSS styling is not maintainable and filled with redundant classes 

**Describe the solution you'd like**
I want to refactor the CSS styles using SASS and also compile the sass file to css using webpack

**Comment by kodekage** [comment]
@samswag please can you invite me to the org. so i can assign myself to the issue and apply the appropriate labels

**Comment by samswag** [comment]
Done

**Comment by samswag** [comment]
@OPARA-PROSPER Are you still working on it?

**Comment by detygon** [comment]
Hi! I would like to work on this. Also, I propose to reduce the selectors' specificity by using classes. There are a lot of tag selectors which might cause issues down the road. Finally, we can improve the structure to avoid the giant single file styles.

**Comment by samswag** [comment]
Sure go ahead

**Comment by detygon** [comment]
Thanks! Do you have a contribution guide?

**Comment by samswag** [comment]
Look at the readme

**Comment by BolajiAyodeji** [comment]
Is this issue still open?
@OPARA-PROSPER @mrdionjr

**Comment by BolajiAyodeji** [comment]
Anyone still working on this?

**Comment by kodekage** [comment]
@BolajiAyodeji i currently cannot work on it now. But will look into when i can

**Comment by BolajiAyodeji** [comment]
Alright, I'll close this now.
Kindly reopen when ready, thanks.
