### ISSUE TITLE
Improve content on the website

### ISSUE THREAD

**Issue by dcoartist** [oscafrica/oscafrica.org-v1#19]
I believe we can always improve the content on the website for better expression

**Comment by samswag** [comment]
Do you want to work on it?

**Comment by dcoartist** [comment]
Yeah, sure.

**Comment by kingisaac95** [comment]
@davidconoh Would be helpful if you assign the issue to yourself so it's clear you're working on it

**Comment by dcoartist** [comment]
@kingisaac95 I am not a member of this organization, just a contributor, so I can't assign issues to myself. Plus, I already made a PR on this which have been reviewed and merged accordingly.
However, contents need to be regularly improved in line with the project's aims and objectives, and everyone interested in the success of this project is welcome to contribute.

**Comment by perriefidelis** [comment]
@davidconoh, are you still working on this?

**Comment by dcoartist** [comment]
Yes, sure. Occasionally.

**Comment by BolajiAyodeji** [comment]
Is this issue still active?

**Comment by dcoartist** [comment]
I don't think so.
