### ISSUE TITLE
Visible mode while navigating on menu.

### ISSUE THREAD

**Issue by samswag** [oscafrica/oscafrica.org-v1#20]
I recent merged someone PR that broke this feature on the page.

<img width="1280" alt="screenshot 2018-11-12 at 12 05 30 pm" src="https://user-images.githubusercontent.com/6048601/48343763-8746ed00-e673-11e8-9e97-8a0a70e71ff1.png">

<img width="1280" alt="screenshot 2018-11-12 at 12 05 15 pm" src="https://user-images.githubusercontent.com/6048601/48343995-2c61c580-e674-11e8-8994-0780c904dd84.png">
<img width="1280" alt="screenshot 2018-11-12 at 12 05 01 pm" src="https://user-images.githubusercontent.com/6048601/48344009-35eb2d80-e674-11e8-958b-32e5d8c490ac.png">

Here is the community page, while navigating on the menu, the element on this page is hidden. While on the other pages it is almost transparent, so a user can see elements on pages like home, About us. This result to too many fixes with on PR. By sending too many fixes in one PR and one commit message it is harder to investigate bugs.

**Comment by fakela** [comment]
`i think i have fixed it https://github.com/oscommunityafrica/oscommunityafrica.github.io/pull/24
