### ISSUE TITLE
Fix alignment in the ABOUT US page

### ISSUE THREAD

**Issue by perriefidelis** [oscafrica/oscafrica.org-v1#9]
**alignment issues**
the Join Us section and footer aren't properly aligned with the rest of the other elements

**align  @left**

<img width="1440" alt="screen shot 2018-11-11 at 5 55 05 pm" src="https://user-images.githubusercontent.com/30669761/48315828-734fac80-e5db-11e8-8cca-bdfe44fa272a.png">

**Comment by BolajiAyodeji** [comment]
@perriefidelis CHECKING

**Comment by BolajiAyodeji** [comment]
This is a bug from the bootstrap modal feature.
Whoever initialized that feature should check it.
I'm still checking. .

**Comment by fakela** [comment]
@perriefidelis just made a fix on that https://github.com/oscommunityafrica/oscommunityafrica.github.io/pull/12

**Comment by samswag** [comment]
<img width="1280" alt="screenshot 2018-11-11 at 10 16 31 pm" src="https://user-images.githubusercontent.com/6048601/48318343-7d83a200-e5ff-11e8-9eb1-470c0575d339.png">
Here is what I tested, I don't think you fixed the issue.

**Comment by BolajiAyodeji** [comment]
@samswag i think the bug is fixed
@fakela thank you for notifying me
![image](https://user-images.githubusercontent.com/30334776/48319751-21764900-e612-11e8-8721-4bd373e213f7.png)

**Comment by BolajiAyodeji** [comment]
can we close this Issue now?
